### ISSUE TITLE
Diferenciar a autenticação em "desenvolvimento" e "produção"

### ISSUE THREAD

**Issue by Tuiuiu** [Kazuo256/monitoria-imeusp#109]
Para poder testar o ambiente de desenvolvimento sem influenciar os dados reais dos usuários

**Comment by Kazuo256** [comment]
Conversei com o Marcelo do Apoio Insitucional para encontrar um jeito de podermos usar paralalelamente as URLs de callback tanto para `localhost` quando pata `monitoria.ime.usp.br`. A princípio, eu esperava usar a autenticação em produção da USP Digital em ambos, mas o Marcelo sugeriu voltar a usar a autenticaçao em desenvolvimento. Pensando bem, o único problema que tivemos com isso é que meu vínculo com a USP apareceia vazio (mas o dos outros desenvolvedores parecia ok). Fora isso, tem o fato que todos precisariam fazer o cadastro em https://labs.uspdigital.usp.br/ para poder usar a autenticação (_não_ é o mesmo que o em produção!).

E é para isso que serve essa issue. Depois eu mando por e-mail as chaves e demais detalhes necessários para usar a autenticação dev da USP.

Um problema que isso trás (ou que já havia antes?) é que não temos como testar o acesso de professores. Se não conseguirmos uma conta para usar, teremos que "transformar" alunos em professores via código _on the fly_ quando o sistema estiver no modo desenvolvimento.
