### ISSUE TITLE
Fazer um seletor melhor de disciplinas quando professor faz pedido

### ISSUE THREAD

**Issue by Kazuo256** [Kazuo256/monitoria-imeusp#80]
Separar por departamento.

**Comment by jacksonjos** [comment]
Você já começou a fazer isso, Wil?
Se não eu código entregar isso até o final de semana.
Le 7 janv. 2015 09:07, "Wilson Kazuo Mizutani" <notifications@github.com> a
écrit :

**Comment by Kazuo256** [comment]
Não fiz ainda não. Na verdade, nem sei como fazer direito. Imagino que precise de JavaScript. Se quiser, manda bala.

Na dúvida, veja se alguém está "assigned" na issue. Se não tiver, marque você mesmo e ela é sua. Se alguém começou e não marcou, é culpa dele por não avisar =P.
